Olwa pr
hms-networks/sc-flexy-tag-info-lib pull request #17
Opened 2020-11-18 14:46 UTC by oliver-walker-hms

2020-11-18 14:57 UTC, alexjhawk requested changes
A commit that updates the javadocs in the docs/ folder also should be added, as the javadocs in that folder are available for public view at https://hms-networks.github.io/sc-flexy-tag-info-lib/index.html

2020-11-18 14:57 UTC, alexjhawk commented on src/com/hms_networks/americas/sc/taginfo/TagInfoManager.java
> +  public static ArrayList getRealTimeTagInfoListFiltered(TagGroup tagGroup) {
missing javadoc for this method

2020-11-18 14:59 UTC, alexjhawk commented
It also looks like you need to rebase this branch with the latest changes

2020-11-18 15:07 UTC, TomKimsey reviewed
Why is realtime log getting added? Are you using it for something in the project you are working on?

2020-11-18 15:11 UTC, TomKimsey commented
> Why is realtime log getting added? Are you using it for something in the project you are working on?

I can see why standard connectors may need some mechanism to configure the polling rate, but the project you are working on has polling rates set in the config file. Having the realtime log enabled will just use resources.

2020-11-18 15:32 UTC, TomKimsey requested changes

2020-11-18 15:32 UTC, TomKimsey commented on src/com/hms_networks/americas/sc/taginfo/TagInfoManager.java
> +import java.io.IOException;
Commit message spelling error : organize

2020-11-19 15:15 UTC, TomKimsey approved these changes

2020-11-19 15:16 UTC, alexjhawk approved these changes

2020-11-19 15:17 UTC, merged